/*----------------------------- DATA DEFINITION Language-----------------------*/
CREATE DATABASE Topmentor;
/* drop DATABASE topmentor;*- drop the database/
use Topmentor;
/* VARCHAR*/
CREATE TABLE EMPL(
EMP_ID INT(20),
EMP_NAME CHAR(30), 
SALARY INT(10));

/* ALTER-CHANGE THE DATATYES AND SIZE OF DATATYES*/
/* 1.change char to varchar DATATYPES*/
ALTER TABLE EMPL modify COLUMN EMP_NAME VARCHAR(10);/* ALTER TABLE EMPL ALTER COLUMN EMP_NAME VARCHAR(10)*/
DESC EMPL;
/* 2.Adding a new column */
ALTER TABLE EMPL ADD COLUMN AGE INT(10);
ALTER TABLE EMPL ADD COLUMN JOB VARCHAR(10);
/* 3.Changing a name */
ALTER TABLE EMPL RENAME COLUMN EMP_ID to EM_IDNO;
/* 4.Droping the column  */
ALTER TABLE EMPL DROP COLUMN JOB;
/*TRUNCATE */
TRUNCATE TABLE EMPL;

/*----------------------------- DATA QUERY Language-----------------------*/
SELECT * FROM EMPL;

/*----------------------------- DATA Manipulation Language-----------------------*/
/* 1.INSERT THE VALUES */
INSERT INTO EMPL VALUES(0,'c#',11000);
INSERT INTO EMPL VALUES(1,'PYTHON',10000);
INSERT INTO EMPL VALUES(2,'JAVA',20000);
INSERT INTO EMPL VALUES(3,'.NET',50000);
INSERT INTO EMPL VALUES(4,'WEB',8000);
INSERT INTO EMPL VALUES(5,'c',80009);

/* 2.UPDATE THE VALUES */
SET SQL_SAFE_UPDATES=0;
UPDATE EMPL SET EMP_NAME='W-DES' WHERE EMP_NAME='WEB';
UPDATE EMPL SET EMP_SALARY=110000 WHERE EMP_SALARY=8000;

/* 3.DELETING THE VALUES FOR 1 ROW */
DELETE FROM EMPL WHERE EM_IDNO=4;
/* DELETING ALL THE VALUES  */
DELETE FROM EMPL;
/*----------------------------- JOIN -----------------------*/
/* creating another table */
CREATE TABLE BRANCH(
BRAN_ID INT(20),
BRAN_NAME CHAR(30), 
SALARY INT(10));
SELECT * FROM BRANCH;
/* 1.INSERT THE VALUES */
INSERT INTO BRANCH VALUES(0,'c++',11000);
INSERT INTO BRANCH VALUES(1,'PY',70000);
INSERT INTO BRANCH VALUES(2,'script',440000);
INSERT INTO BRANCH VALUES(3,'dot',550000);
INSERT INTO BRANCH VALUES(4,'WEBs',80000);
INSERT INTO BRANCH VALUES(5,'c',80009);
SELECT * FROM EMPL;
SELECT * FROM BRANCH;

/* USE INNER JOIN TO PULL COMMON DATA OUTSIDE FORM OUTSIDE THE TABLE */
SELECT * FROM EMPL INNER JOIN BRANCH ON EMPL.SALARY = BRANCH.SALARY;
/* RETRIVEING THE MATCHING DATA FROM ALL TABLES AND UNMATCHING THE TABLE FROM LEFT OUTER JOIN*/
SELECT *FROM EMPL E LEFT OUTER JOIN BRANCH  B ON E.SALARY=B.SALARY;/* ONLY COMMON VALUES TAKEN REMAINING NULL IN LEFT OUTER JOIN */
/* ONLY COMMON VALUES TAKEN REMAINING NULL IN RIGHT OUTER JOIN */
SELECT * FROM EMPL E RIGHT OUTER JOIN BRANCH B ON E.SALARY=B.SALARY;
